# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('main_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='publishers',
            name='writers',
            field=models.ManyToManyField(to='apone.Writers'),
        ),
        migrations.AddField(
            model_name='books',
            name='pub_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apone.Publishers'),
        ),
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apone.Writers'),
        ),
    ]
