# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('apone', '0002_auto_20180401_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishers',
            name='writers',
        ),
    ]
