# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-02 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apone', '0003_remove_publishers_writers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='writer',
        ),
        migrations.AddField(
            model_name='books',
            name='writer',
            field=models.ManyToManyField(to='apone.Writers'),
        ),
    ]
