# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apone', '0004_auto_20180402_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='writer',
        ),
        migrations.AddField(
            model_name='writers',
            name='books',
            field=models.ManyToManyField(to='apone.Books'),
        ),
    ]
