# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-05 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apone', '0005_auto_20180405_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(default=9.9),
            preserve_default=False,
        ),
    ]
